import { createClient } from '@supabase/supabase-js'
import { generateText, generateJSON } from '../lib/ai'
import { Octokit } from '@octokit/rest'

const db = createClient(
  process.env.SUPABASE_URL || 'https://placeholder.supabase.co',
  process.env.SUPABASE_SERVICE_KEY || 'placeholder'
)

async function logAgent(name: string, action: string, result: string, status: 'success' | 'error', error?: string): Promise<void> {
  try {
    await db.from('agent_logs').insert({ agent_name: name, action, result, status, error: error || null })
  } catch {}
}

export async function runSelfUpdate(): Promise<{ updated: boolean; prUrl?: string; summary: string }> {
  const token = process.env.GITHUB_TOKEN
  const owner = process.env.GITHUB_OWNER || ''
  const repo = process.env.GITHUB_REPO || 'worker-ai'

  if (!token || token === 'placeholder' || !owner) {
    return { updated: false, summary: 'GitHub not configured' }
  }

  await logAgent('self_update', 'analyzing', 'Reviewing agent error logs', 'success')

  try {
    const { data: logs } = await db
      .from('agent_logs')
      .select('agent_name, action, status, error, created_at')
      .eq('status', 'error')
      .order('created_at', { ascending: false })
      .limit(20)

    const errorLogs = logs && Array.isArray(logs) ? logs : []

    if (errorLogs.length === 0) {
      await logAgent('self_update', 'no_errors', 'System healthy', 'success')
      return { updated: false, summary: 'No errors found. System is healthy.' }
    }

    const logSummary = errorLogs
      .slice(0, 8)
      .map(l => l.agent_name + ':' + l.action + ':' + (l.error || 'error').slice(0, 60))
      .join('\n')

    let parsed: any = null
    try {
      parsed = await generateJSON(
        'Analyze these agent errors and identify ONE improvement to make. Return JSON only: {"file":"agents/research.ts","issue":"description of problem","fix":"description of fix"}\n\nErrors:\n' + logSummary,
        300
      )
    } catch {
      return { updated: false, summary: 'Could not analyze errors: ' + errorLogs[0]?.action }
    }

    if (!parsed || !parsed.file) {
      return { updated: false, summary: 'No actionable improvements identified' }
    }

    const octokit = new Octokit({ auth: token })

    let existingContent = ''
    let existingSha: string | undefined

    try {
      const fileRes = await octokit.repos.getContent({ owner, repo, path: parsed.file })
      existingContent = Buffer.from((fileRes.data as any).content, 'base64').toString('utf-8')
      existingSha = (fileRes.data as any).sha
    } catch {
      return { updated: false, summary: 'Could not read file: ' + parsed.file }
    }

    const branchName = 'auto-fix-' + Date.now()

    try {
      const mainRef = await octokit.repos.getBranch({ owner, repo, branch: 'main' })
      await octokit.git.createRef({
        owner, repo,
        ref: 'refs/heads/' + branchName,
        sha: mainRef.data.commit.sha
      })
    } catch (e: any) {
      return { updated: false, summary: 'Could not create branch: ' + e.message }
    }

    let fixedCode = ''
    try {
      fixedCode = await generateText(
        'Fix this TypeScript file to address: ' + parsed.issue + '\n\nFix approach: ' + parsed.fix + '\n\nCurrent file:\n' + existingContent.slice(0, 3000) + '\n\nReturn ONLY the complete fixed TypeScript file. No markdown fences.',
        4096
      )
      fixedCode = fixedCode
        .replace(/^```(?:typescript|ts)?\n?/gm, '')
        .replace(/```$/gm, '')
        .trim()
    } catch {
      return { updated: false, summary: 'Could not generate fix for: ' + parsed.file }
    }

    if (!fixedCode || fixedCode.length < 100) {
      return { updated: false, summary: 'Generated fix was too short, skipping' }
    }

    try {
      await octokit.repos.createOrUpdateFileContents({
        owner, repo,
        path: parsed.file,
        message: 'Auto-fix: ' + parsed.fix,
        content: Buffer.from(fixedCode).toString('base64'),
        branch: branchName,
        ...(existingSha ? { sha: existingSha } : {})
      })
    } catch (e: any) {
      return { updated: false, summary: 'Could not commit fix: ' + e.message }
    }

    let prUrl = ''
    try {
      const pr = await octokit.pulls.create({
        owner, repo,
        title: 'Auto-improvement: ' + parsed.fix.slice(0, 60),
        body: 'Automatic fix for: ' + parsed.issue + '\n\nGenerated by Worker AI self-update agent.',
        head: branchName,
        base: 'main'
      })
      prUrl = pr.data.html_url
    } catch {}

    await logAgent('self_update', 'pr_created', prUrl || branchName, 'success')
    return { updated: true, prUrl, summary: 'Fixed: ' + parsed.fix }

  } catch (e: any) {
    await logAgent('self_update', 'failed', e.message, 'error', e.message)
    return { updated: false, summary: 'Self-update failed: ' + e.message }
  }
}
